
exclude:
  - vendor/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  style: compressed

author: Adriane Justine Tan
email: eidoriantan@gmail.com
repository: eidoriantan/typer

tagline: Simple typing game for browsers
color: "#24292e"

plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap
